version: '3.8'
services:
  public-api-service:
    build: ./PublicAPI
    working_dir: /app
    volumes:
      - ./PublicAPI:/app
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      FLASK_ENV: development
    # command: tail -f /dev/null
    command: gunicorn -b 0.0.0.0:5000 index:app --reload
  
  travel-optimizer-service:
    build: ./TravelOptimizerService
    working_dir: /app
    volumes:
      - ./TravelOptimizerService:/app
    ports:
      - "5002:5000"
    networks:
      - app-network
    environment:
      FLASK_ENV: development
    # command: tail -f /dev/null
    command: gunicorn -b 0.0.0.0:5000 index:app --reload

  voice-recognition-service:
    build: ./VoiceRecognitionService
    working_dir: /app
    volumes:
      - ./VoiceRecognitionService:/app
    ports:
      - "5003:5000"
    networks:
      - app-network
    environment:
      FLASK_ENV: development

    # command: tail -f /dev/null
    command: gunicorn -b 0.0.0.0:5000 index:app --reload

  nlp-service:
    build: ./NLPService
    working_dir: /app
    volumes:
      - ./NLPService:/app
    ports:
      - "5004:5000"
    networks:
      - app-network
    environment:
      FLASK_ENV: development
    # command: tail -f /dev/null
    command: gunicorn -b 0.0.0.0:5000 index:app --reload

networks:
  app-network:
    driver: bridge