apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  rules:
  - host: "*"
    http:
      paths:
      - path: /nlp-service
        pathType: Prefix
        backend:
          service:
            name: nlp-service
            port:
              number: 5000
      - path: /voice-recognition-service
        pathType: Prefix
        backend:
          service:
            name: voice-recognition-service
            port:
              number: 5000
      - path: /travel-optimizer-service
        pathType: Prefix
        backend:
          service:
            name: travel-optimizer-service
            port:
              number: 5000
      - path: /public-api-service
        pathType: Prefix
        backend:
          service:
            name: public-api-service
            port:
              number: 5000
