# syntax=docker/dockerfile:1.4
FROM python:3.9-slim-buster

USER root

WORKDIR /app

COPY . /app
COPY requirements.txt /app

RUN apt-get update && apt-get install -y ffmpeg
RUN python3 -m pip install -r requirements.txt
